#! /bin/sh

sxhkd &

compton --config ~/.config/compton/compton.conf &
feh --bg-center ~/Docfiles/lain_wal.png &

~/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp-2.8 state=floating follow= on focus=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color \#48D1CC
bspc config active_border_color \#00CDFA
bspc config focused_border_color \#00CDFA
bspc config presel_feedback_color \#48D1CC
